name: Run benchmarks

on:
  - push

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x  # Adjust the .NET version if needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Benchmarks
        run: dotnet run --configuration Release --project Distances.Benchmarks

      - name: Save Benchmark.NET results as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: ./BenchmarkDotNet.Artifacts/results/